### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by kai-niessen** [HaikuArchives/Sequitur#4]
Mainly because of missing classes ArpMidiEvent (interface and derivates) and ArpMidiNode , but also various errors regarding include files and deprecated functions.

**Comment by waddlesplash** [comment]
Last I checked, `master` does compile, and there's a working recipe for it. Are you on GCC4?

**Comment by waddlesplash** [comment]
Huh, it is broken. I'll have a look.

**Comment by kai-niessen** [comment]
Hey that's fast!

No, I'm on gcc2. I found ArpMidiEvent and -Node classes missing. They are pretty obvious, so I reengineered them from the method calls in other classes and finally got a working binary. 
Tried to attach the diff to a comment but would that makes Web+ crash.

**Comment by kai-niessen** [comment]
The version on HaikuDepot complains about a missing symbol related to blend_color that seems to have disappeared in newer Hailu revisions.

**Comment by kai-niessen** [comment]
Trying to attach diff using Qupzilla...

**Comment by waddlesplash** [comment]
Yes, it has, but that should've only been a recompile. Wonder what else broke. Probably should rewrite the whole makefile system anyway.

**Comment by waddlesplash** [comment]
fyi, I'll be on Freenode#haiku for the next while.

**Comment by waddlesplash** [comment]
OK, so 64908b10ed4bbd0401861948b0581fe67856a15e improves things significantly; it now gets to the link stage but fails with lots of undefined symbols, which makes no sense because those should be provided by libcolumnlistview... the name mangling looks the same so I've no idea what's going on.

**Comment by kai-niessen** [comment]
That's a huge commit...
Great you switched the proprietary code for columnlistview and  color manipulation to the existing system variants. 
Still, the ArpMidi2 and ArpMidiPublic directories are missing, maybe that's where the undefined symbols errors are coming from.

**Comment by waddlesplash** [comment]
>  Great you switched the proprietary code for columnlistview and color manipulation to the existing system variants. 

They were under Be Sample Code License aka. Modified BSD, so not exactly "proprietary". The system variants are just updated versions of the same classes.

> Still, the ArpMidi2 and ArpMidiPublic directories are missing, maybe that's where the undefined symbols errors are coming from.

You need to run `make` in `Sequitur`, not in the repository root. And no, the undefined symbols are most definitely from the column list view.

**Comment by kai-niessen** [comment]
Ok, ran a pull/stash- As you say, undefined references all point to ColumnListview related things. Will however not produce a suiccessully launchabel binary.
Amyway, great to see you that present, Sequitur is in my eyes a ver powerful and still very unique application.

**Comment by kai-niessen** [comment]
Seems that the -lcolumnlistview is not effective. If I copy the failed linker command and move 
-lcolumnlistview to the end, it works - maybe a bug in gcc/ld? As a workaround, I have put it into the Be Static Lib area. 

ADD_BESTLIBS	= $(shell findpaths -r "makefile_engine"  B_FIND_PATH_DEVELOP_LIB_DIRECTORY)/libcolumnlistview.a

**Comment by waddlesplash** [comment]
Fixed in c5907949806d70f4888f4c47cffcd3eefce48c4c.
