### ISSUE TITLE
Add pitch and velocity add-ons

### ISSUE THREAD

**Issue by richienyhus** [HaikuArchives/Sequitur#5]
[ArpVaccineV-x86_src-incl.zip](https://github.com/HaikuArchives/Sequitur/files/321728/ArpVaccineV-x86_src-incl.zip)
[ArpVaccineP-x86_src-incl.zip](https://github.com/HaikuArchives/Sequitur/files/321729/ArpVaccineP-x86_src-incl.zip)

**Comment by humdingerb** [comment]
From the Sequitur v2.1 release notes, it appears those filters are deprecated:

> The Vaccine.P and Vaccine.V filters have been deprecated (although they are	still available at http://www.angryredplanet.com/beos/Sequitur/Filters).  They are replaced by the Vaccine filter.  In addition to	injecting a motion into the pitch and velocity of notes, this new filter can inject it into control change, pitch bend, tempo change and channel pressure events.  The new tool Broken Down Line uses this filter.

**Comment by richienyhus** [comment]
I suppose this should be closed then.

Are the tools: "Transpose Up";  "Transpose Down";  "One Track Pencil"; "Eat Duplicates" and "Unstack" located anywhere else ? (apart from on the tools page [here](http://www.angryredplanet.com/beos/Sequitur/Tools/) )

If not, maybe they could be made into an extras package ?

**Comment by humdingerb** [comment]
I see no reason to not just put those tools into the main package. Hold the PR...

**Comment by humdingerb** [comment]
Done. This and the other issue with the vector icon can be closed when the PR is merged.
