### ISSUE TITLE
Vector icon (attached)

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Sequitur#7]
Attached is an I-O-M file of a vector version of the app icon.
I'm unsure how to apply it to the .rsrc file...

[Sequitur-iom.zip](https://github.com/HaikuArchives/Sequitur/files/527609/Sequitur-iom.zip)

**Comment by scottmc** [comment]
Try to open it in I-O-M, then export as an href file.  Convert the .rsrc to an .rdef.  This should be done anyways as it's better to have the text version in the repo instead of the binary .rsrc file.  See https://www.haiku-os.org/documents/dev/compile_them_resources

**Comment by humdingerb** [comment]
[Sequitur.rdef.txt](https://github.com/HaikuArchives/Sequitur/files/527791/Sequitur.rdef.txt)

I just removed the mini and large icon from the rsrc and put in the vector icon instead. Unfortunately I get lost in the makefile jungle. Where do I replace the rsrc with the rdef...?

**Comment by scottmc** [comment]
You can decompile the rsrc file to turn it into an .rdef file.  From there you can use a text editor to modify and/or remove sections.  

Snipette from the above linked article:
To decompile, type the following from a Terminal window:
rc -d -o outputfile.rdef inputfile.rsrc

**Comment by humdingerb** [comment]
yes. that's exactly how I did arrive at the attached rdef. :)
The thing is that I don't know how to get the rdef used instead of the rsrc. It all does work if I compile my rdef back to rsrc...

**Comment by scottmc** [comment]
It's easy if using the makefile engine, but this one does seem to be.  Anyone else know how to handle this?

**Comment by humdingerb** [comment]
Yeah. i tried putting a RDEF entry with "Sequitur" into MakeApp, but that isn't picked up...

**Comment by waddlesplash** [comment]
Fixed in PR.
