### ISSUE TITLE
x64 support

### ISSUE THREAD

**Issue by extrowerk** [HaikuArchives/Sequitur#9]
It would be nice to have Sequitur on x86_64 Haiku. Any chance?

**Comment by ilzu** [comment]
Here is a quick and dirty patch to make Sequitur compile on x86_64. It doesn't work though: it crashes on start when initializing devices, but it's a start for getting it to work. I might look at it more someday and add new patches.
[sequitur-64bit.zip](https://github.com/HaikuArchives/Sequitur/files/7225021/sequitur-64bit.zip)

**Comment by ilzu** [comment]
Here is updated patch to get Sequitur to compile on 64 bit, this one compiles on 32bit (with both gcc2 and gcc 8.3) and on 64 bit. The gcc2 32 bit version seems to work (I didn't test that throughly yet) but gcc 8.3 version crashes on both 32 bit and 64 bit during startup while loading devices. I'll try to debug and find out and fix what causes the crash. 
[Sequitur-64bit-20210925.patch.zip](https://github.com/HaikuArchives/Sequitur/files/7230300/Sequitur-64bit-20210925.patch.zip)

**Comment by ilzu** [comment]
I made a pull request for this ( #11 )

**Comment by Brunobasta** [comment]
Hey nice does it work now?

**Comment by ilzu** [comment]
Yep, it works, at least with everything I have tested so far.

**Comment by Brunobasta** [comment]
When will it be on HaikuDepot?

**Comment by diversys** [comment]
Fixed in 93c948627b24a325e4e744dad27503260a8a3d1f.

**Comment by Brunobasta** [comment]
It works on 64bit for some time, close!
